Add `workflow_dispatch` trigger for CI (#9)
This enables manual CI runs, optionally including deploys.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -5,7 +5,14 @@ on:
     branches:
       - main
   pull_request:
-
+  workflow_dispatch:
+    inputs:
+      perform_deploy:
+        description: "Deploy to production"
+        required: true
+        type: boolean
+        default: false
+        
 jobs:
   test:
     name: Run tests
@@ -38,12 +45,75 @@ jobs:
         >> $GITHUB_STEP_SUMMARY go tool cover -func=${{ github.workspace }}/coverage.out
         >> $GITHUB_STEP_SUMMARY echo '```'
 
+  decision:
+    name: Decide whether to deploy
+    runs-on: ubuntu-latest
+    needs:
+      - test
+    outputs:
+      deploy: ${{ steps.decide.outputs.deploy }}
+    steps:
+      - id: decide
+        name: Decide
+        env:
+          TEST_RESULT: ${{ needs.test.result }}
+          WAS_PUSH_TO_MAIN: ${{ github.event_name == 'push' && github.ref_name == 'main' && github.ref_type == 'branch' }}
+          WAS_DEPLOY_REQUESTED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.perform_deploy }}
+          
+        run: |
+          >> $GITHUB_STEP_SUMMARY cat << "EOF"
+
+          ### Trigger
+          Event: `${{ github.event_name }}`
+          Ref:   `${{ github.ref}}`
+
+          ### Environment
+
+          ```
+          EOF
+
+          >> $GITHUB_STEP_SUMMARY cat << EOF
+          TEST_RESULT="$TEST_RESULT" 
+          WAS_PUSH_TO_MAIN="$WAS_PUSH_TO_MAIN"
+          WAS_DEPLOY_REQUESTED="$WAS_DEPLOY_REQUESTED"
+          EOF
+
+          >> $GITHUB_STEP_SUMMARY echo '```'
+          >> $GITHUB_STEP_SUMMARY echo ""
+
+          if ! [ "$TEST_RESULT" = "success" ]; then
+            >> $GITHUB_STEP_SUMMARY echo "Tests failed."
+            >> $GITHUB_STEP_SUMMARY echo "Not deploying."
+            >> $GITHUB_OUTPUT echo "deploy=false"
+            exit 0
+          else
+            >> $GITHUB_STEP_SUMMARY echo "Tests passed."
+          fi
+
+          if [ "$WAS_PUSH_TO_MAIN" = "true" ] ; then
+            >> $GITHUB_STEP_SUMMARY echo "Triggered by push to main."
+            >> $GITHUB_STEP_SUMMARY echo "Deploying to production."
+            >> $GITHUB_OUTPUT echo "deploy=true"
+            exit 0
+          fi
+          
+          if [ "$WAS_DEPLOY_REQUESTED" = "true" ]; then
+            >> $GITHUB_STEP_SUMMARY echo "Triggered by manual request."
+            >> $GITHUB_STEP_SUMMARY echo "Deployment to production was requested."
+            >> $GITHUB_STEP_SUMMARY echo "Deploying to production."
+            >> $GITHUB_OUTPUT echo "deploy=true"
+            exit 0
+          fi
+
+          >> $GITHUB_STEP_SUMMARY echo "Not deploying."
+          >> $GITHUB_OUTPUT echo "deploy=false"
+
   deploy:
     name: Deploy to Fly.io
     runs-on: ubuntu-latest
     needs:
-      - test
-    if: ${{ needs.test.result == 'success' && github.event_name == 'push' && github.ref_name == 'main' && github.ref_type == 'branch' }}
+      - decision
+    if: ${{ needs.decision.deploy == 'true' }}
     environment: production
     concurrency:
       group: deploy-${{ vars.ENVIRONMENT_NAME }}
@@ -76,27 +146,3 @@ jobs:
         mv ../config/config.json ./config.json
         mv ../config/fly.toml ./fly.toml
         flyctl deploy --remote-only
-
-  explain:
-    name: Explain lack of deploy
-    runs-on: ubuntu-latest
-    needs:
-      - test
-    if: ${{ needs.test.result != 'success' || github.event_name != 'push' || github.ref_name != 'main' || github.ref_type != 'branch' }}
-    steps:
-    - name: Summarize deploy skip
-      if: ${{ needs.test.result == 'success' && (github.ref_name != 'main' || github.ref_type != 'branch') }}
-      run: |
-        >> $GITHUB_STEP_SUMMARY cat <<EOF
-        Deploy **skipped** because this was not a push to main.
-        Event: ${{ github.event_name }}
-        Ref:   ${{ github.ref}}
-        EOF
-    - name: Summarize deploy skip
-      if: ${{ needs.test.result != 'success' }}
-      run: |
-        >> $GITHUB_STEP_SUMMARY cat <<EOF
-        Deploy **skipped** because tests failed.
-        Event: ${{ github.event_name }}
-        Ref:   ${{ github.ref}}
-        EOF
